INSERT INTO book (id, name, author, price) VALUES (1001, 'The Great Gatsby', 'F. Scott Fitzgerald', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1002, 'To Kill a Mockingbird', 'Harper Lee', 12.49);
INSERT INTO book (id, name, author, price) VALUES (1003, '1984', 'George Orwell', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1004, 'The Catcher in the Rye', 'J.D. Salinger', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1005, 'Pride and Prejudice', 'Jane Austen', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1006, 'Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 14.99);
INSERT INTO book (id, name, author, price) VALUES (1007, 'The Hobbit', 'J.R.R. Tolkien', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1008, 'The Lord of the Rings', 'J.R.R. Tolkien', 29.99);
INSERT INTO book (id, name, author, price) VALUES (1009, 'The Da Vinci Code', 'Dan Brown', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1010, 'The Alchemist', 'Paulo Coelho', 13.99);
INSERT INTO book (id, name, author, price) VALUES (1011, 'The Adventures of Tom Sawyer', 'Mark Twain', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1012, 'Moby-Dick', 'Herman Melville', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1013, 'The Odyssey', 'Homer', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1014, 'The Great Expectations', 'Charles Dickens', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1015, 'Crime and Punishment', 'Fyodor Dostoevsky', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1016, 'The Picture of Dorian Gray', 'Oscar Wilde', 8.49);
INSERT INTO book (id, name, author, price) VALUES (1017, 'Brave New World', 'Aldous Huxley', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1018, 'The Divine Comedy', 'Dante Alighieri', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1019, 'The Chronicles of Narnia', 'C.S. Lewis', 16.99);
INSERT INTO book (id, name, author, price) VALUES (1020, 'A Tale of Two Cities', 'Charles Dickens', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1021, 'The Little Prince', 'Antoine de Saint-Exupéry', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1022, 'The Hunger Games', 'Suzanne Collins', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1023, 'The Kite Runner', 'Khaled Hosseini', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1024, 'Lord of the Flies', 'William Golding', 8.49);
INSERT INTO book (id, name, author, price) VALUES (1025, 'Gone with the Wind', 'Margaret Mitchell', 13.49);
INSERT INTO book (id, name, author, price) VALUES (1026, 'The Shining', 'Stephen King', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1027, 'A Game of Thrones', 'George R.R. Martin', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1028, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1029, 'The Fault in Our Stars', 'John Green', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1030, 'The Hitchhiker''s Guide to the Galaxy', 'Douglas Adams', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1031, 'The Secret Life of Bees', 'Sue Monk Kidd', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1032, 'The Count of Monte Cristo', 'Alexandre Dumas', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1033, 'The Diary of a Young Girl', 'Anne Frank', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1034, 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 14.99);
INSERT INTO book (id, name, author, price) VALUES (1035, 'The Sun Also Rises', 'Ernest Hemingway', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1036, 'The Handmaid''s Tale', 'Margaret Atwood', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1037, 'The Old Man and the Sea', 'Ernest Hemingway', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1038, 'The Road', 'Cormac McCarthy', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1039, 'The Scarlet Letter', 'Nathaniel Hawthorne', 9.49);
INSERT INTO book (id, name, author, price) VALUES (1040, 'The Adventures of Huckleberry Finn', 'Mark Twain', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1041, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1042, 'The Giver', 'Lois Lowry', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1043, 'The Grapes of Wrath', 'John Steinbeck', 10.49);
INSERT INTO book (id, name, author, price) VALUES (1044, 'The Girl on the Train', 'Paula Hawkins', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1045, 'The Joy Luck Club', 'Amy Tan', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1046, 'The Lovely Bones', 'Alice Sebold', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1047, 'The Maze Runner', 'James Dashner', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1048, 'The Name of the Wind', 'Patrick Rothfuss', 13.99);
INSERT INTO book (id, name, author, price) VALUES (1049, 'The Outsiders', 'S.E. Hinton', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1050, 'The Road Less Traveled', 'M. Scott Peck', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1051, 'The Secret', 'Rhonda Byrne', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1052, 'The Stand', 'Stephen King', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1053, 'The Stranger', 'Albert Camus', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1054, 'The Time Traveler''s Wife', 'Audrey Niffenegger', 12.49);
INSERT INTO book (id, name, author, price) VALUES (1055, 'The Unbearable Lightness of Being', 'Milan Kundera', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1056, 'The War of the Worlds', 'H.G. Wells', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1057, 'The Wind-Up Bird Chronicle', 'Haruki Murakami', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1058, 'Things Fall Apart', 'Chinua Achebe', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1059, 'To the Lighthouse', 'Virginia Woolf', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1060, 'Treasure Island', 'Robert Louis Stevenson', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1061, 'Twilight', 'Stephenie Meyer', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1062, 'Ulysses', 'James Joyce', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1063, 'Wuthering Heights', 'Emily Bronte', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1064, 'The Adventures of Sherlock Holmes', 'Arthur Conan Doyle', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1065, 'The Canterbury Tales', 'Geoffrey Chaucer', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1066, 'The Color Purple', 'Alice Walker', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1067, 'The Fault in Our Stars', 'John Green', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1068, 'The Fellowship of the Ring', 'J.R.R. Tolkien', 14.99);
INSERT INTO book (id, name, author, price) VALUES (1069, 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1070, 'The Great Expectations', 'Charles Dickens', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1071, 'The Grapes of Wrath', 'John Steinbeck', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1072, 'The Great Gatsby', 'F. Scott Fitzgerald', 8.49);
INSERT INTO book (id, name, author, price) VALUES (1073, 'The Hobbit', 'J.R.R. Tolkien', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1074, 'The Hunger Games', 'Suzanne Collins', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1075, 'The Iliad', 'Homer', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1076, 'The Jungle Book', 'Rudyard Kipling', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1077, 'The Lord of the Rings', 'J.R.R. Tolkien', 19.99);
INSERT INTO book (id, name, author, price) VALUES (1078, 'The Little Prince', 'Antoine de Saint-Exupéry', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1079, 'The Martian', 'Andy Weir', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1080, 'The Odyssey', 'Homer', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1081, 'The Old Man and the Sea', 'Ernest Hemingway', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1082, 'The Picture of Dorian Gray', 'Oscar Wilde', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1083, 'The Secret Garden', 'Frances Hodgson Burnett', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1084, 'The Silmarillion', 'J.R.R. Tolkien', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1085, 'The Sisters Brothers', 'Patrick deWitt', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1086, 'The Sound and the Fury', 'William Faulkner', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1087, 'The Stranger', 'Albert Camus', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1088, 'The Sun Also Rises', 'Ernest Hemingway', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1089, 'The Tell-Tale Heart', 'Edgar Allan Poe', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1090, 'The Time Machine', 'H.G. Wells', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1091, 'The Trial', 'Franz Kafka', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1092, 'The Unbearable Lightness of Being', 'Milan Kundera', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1093, 'The War of the Worlds', 'H.G. Wells', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1094, 'The Waste Land', 'T.S. Eliot', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1095, 'The Wind in the Willows', 'Kenneth Grahame', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1096, 'The Wonderful Wizard of Oz', 'L. Frank Baum', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1097, 'The World According to Garp', 'John Irving', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1098, 'Their Eyes Were Watching God', 'Zora Neale Hurston', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1099, 'Things Fall Apart', 'Chinua Achebe', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1100, 'To Kill a Mockingbird', 'Harper Lee', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1101, 'Treasure Island', 'Robert Louis Stevenson', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1102, 'Twilight', 'Stephenie Meyer', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1103, 'Ulysses', 'James Joyce', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1104, 'Uncle Tom''s Cabin', 'Harriet Beecher Stowe', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1105, 'Vanity Fair', 'William Makepeace Thackeray', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1106, 'Walden', 'Henry David Thoreau', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1107, 'War and Peace', 'Leo Tolstoy', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1108, 'Water for Elephants', 'Sara Gruen', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1109, 'Where the Sidewalk Ends', 'Shel Silverstein', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1110, 'White Fang', 'Jack London', 7.99);
INSERT INTO book (id, name, author, price) VALUES (1111, 'Winnie-the-Pooh', 'A.A. Milne', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1112, 'Wuthering Heights', 'Emily Bronte', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1113, 'Zen and the Art of Motorcycle Maintenance', 'Robert M. Pirsig', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1114, 'The Book Thief', 'Markus Zusak', 12.49);
INSERT INTO book (id, name, author, price) VALUES (1115, 'The Chronicles of Narnia', 'C.S. Lewis', 13.99);
INSERT INTO book (id, name, author, price) VALUES (1116, 'The Curious Incident of the Dog in the Night-Time', 'Mark Haddon', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1117, 'The Fault in Our Stars', 'John Green', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1118, 'The Godfather', 'Mario Puzo', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1119, 'The Handmaid''s Tale', 'Margaret Atwood', 10.99);
INSERT INTO book (id, name, author, price) VALUES (1120, 'The Hobbit', 'J.R.R. Tolkien', 11.99);
INSERT INTO book (id, name, author, price) VALUES (1121, 'The Hunger Games', 'Suzanne Collins', 12.99);
INSERT INTO book (id, name, author, price) VALUES (1122, 'The Lord of the Rings', 'J.R.R. Tolkien', 19.99);
INSERT INTO book (id, name, author, price) VALUES (1123, 'The Odyssey', 'Homer', 9.99);
INSERT INTO book (id, name, author, price) VALUES (1124, 'The Picture of Dorian Gray', 'Oscar Wilde', 8.99);
INSERT INTO book (id, name, author, price) VALUES (1125, 'The Secret Life of Bees', 'Sue Monk Kidd', 11.49);
INSERT INTO book (id, name, author, price) VALUES (1126, 'The Silmarillion', 'J.R.R. Tolkien', 10.99);




